export const productsData = {
    totalProducts: 3456,
    lowStockProducts: 45,
    outOfStockProducts: 12,
    productList: [
        {
            id: 1,
            name: "Wireless Headphones",
            category: "Electronics",
            price: "₹4,999",
            stock: 25,
            status: "In Stock",
            lastRestocked: "2024-02-15",
            totalSales: 150,
            revenue: "₹7,49,850",
        },
        {
            id: 2,
            name: "Smart Watch",
            category: "Electronics",
            price: "₹2,499",
            stock: 5,
            status: "Low Stock",
            lastRestocked: "2024-02-20",
            totalSales: 200,
            revenue: "₹4,99,800",
        },
        {
            id: 3,
            name: "Bluetooth Speaker",
            category: "Electronics",
            price: "₹1,999",
            stock: 0,
            status: "Out of Stock",
            lastRestocked: "2024-02-10",
            totalSales: 100,
            revenue: "₹1,99,900",
        },
    ],
    productStats: {
        topSellingProduct: "Wireless Headphones",
        averageProductPrice: "₹3,166",
        totalInventoryValue: "₹1,09,44,096",
        categories: ["Electronics", "Accessories", "Gadgets"],
    },
}; 