export const reportsData = {
    recentReports: [
        {
            id: 1,
            title: "Monthly Sales Report",
            date: "2024-03-15",
            status: "Completed",
            type: "Sales",
            downloadUrl: "#",
            size: "2.5 MB",
            generatedBy: "System",
        },
        {
            id: 2,
            title: "Customer Analysis Q1",
            date: "2024-03-10",
            status: "In Progress",
            type: "Analytics",
            downloadUrl: "#",
            size: "1.8 MB",
            generatedBy: "Admin",
        },
        {
            id: 3,
            title: "Inventory Status",
            date: "2024-03-05",
            status: "Completed",
            type: "Inventory",
            downloadUrl: "#",
            size: "3.2 MB",
            generatedBy: "System",
        },
    ],
    reportTemplates: [
        {
            id: 1,
            name: "Sales Summary",
            description: "Daily sales summary report",
            lastUsed: "2024-03-14",
            format: "PDF",
            schedule: "Daily",
        },
        {
            id: 2,
            name: "Customer Insights",
            description: "Customer behavior analysis",
            lastUsed: "2024-03-12",
            format: "Excel",
            schedule: "Weekly",
        },
        {
            id: 3,
            name: "Inventory Report",
            description: "Stock level analysis",
            lastUsed: "2024-03-10",
            format: "PDF",
            schedule: "Monthly",
        },
    ],
    reportCategories: [
        {
            id: 1,
            name: "Sales Reports",
            count: 15,
            lastUpdated: "2024-03-15",
        },
        {
            id: 2,
            name: "Customer Reports",
            count: 8,
            lastUpdated: "2024-03-14",
        },
        {
            id: 3,
            name: "Inventory Reports",
            count: 12,
            lastUpdated: "2024-03-13",
        },
    ],
}; 